// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace Compiler.Specs.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class СтруктурыFeature : object, global::Xunit.IClassFixture<СтруктурыFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("ru"), "Features", "структуры", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "Structs.feature"
#line hidden
        
        public СтруктурыFeature(СтруктурыFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Structs.feature.ndjson", 20);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="объявление структуры, литерал, чтение int-полей")]
        [global::Xunit.TraitAttribute("FeatureTitle", "структуры")]
        [global::Xunit.TraitAttribute("Description", "объявление структуры, литерал, чтение int-полей")]
        public async global::System.Threading.Tasks.Task ОбъявлениеСтруктурыЛитералЧтениеInt_Полей()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("объявление структуры, литерал, чтение int-полей", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 4
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
        await testRunner.GivenAsync("я скомпилировал программу \"features/structs/struct_int_fields.ww\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Пусть ");
#line hidden
#line 6
        await testRunner.WhenAsync("я выполняю программу", ((string)(null)), ((global::Reqnroll.Table)(null)), "Когда ");
#line hidden
#line 7
        await testRunner.ThenAsync("я увижу вывод 1020", ((string)(null)), ((global::Reqnroll.Table)(null)), "Тогда ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="литерал структуры со string и bool")]
        [global::Xunit.TraitAttribute("FeatureTitle", "структуры")]
        [global::Xunit.TraitAttribute("Description", "литерал структуры со string и bool")]
        public async global::System.Threading.Tasks.Task ЛитералСтруктурыСоStringИBool()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("литерал структуры со string и bool", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 9
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 10
        await testRunner.GivenAsync("я скомпилировал программу \"features/structs/struct_string_bool.ww\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Пусть ");
#line hidden
#line 11
        await testRunner.WhenAsync("я выполняю программу", ((string)(null)), ((global::Reqnroll.Table)(null)), "Когда ");
#line hidden
#line 12
        await testRunner.ThenAsync("я увижу вывод Alicetrue", ((string)(null)), ((global::Reqnroll.Table)(null)), "Тогда ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="запись в поле структуры")]
        [global::Xunit.TraitAttribute("FeatureTitle", "структуры")]
        [global::Xunit.TraitAttribute("Description", "запись в поле структуры")]
        public async global::System.Threading.Tasks.Task ЗаписьВПолеСтруктуры()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("запись в поле структуры", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 14
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 15
        await testRunner.GivenAsync("я скомпилировал программу \"features/structs/struct_write_field.ww\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Пусть ");
#line hidden
#line 16
        await testRunner.WhenAsync("я выполняю программу", ((string)(null)), ((global::Reqnroll.Table)(null)), "Когда ");
#line hidden
#line 17
        await testRunner.ThenAsync("я увижу вывод 52", ((string)(null)), ((global::Reqnroll.Table)(null)), "Тогда ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="запись в поле через выражение с другим полем")]
        [global::Xunit.TraitAttribute("FeatureTitle", "структуры")]
        [global::Xunit.TraitAttribute("Description", "запись в поле через выражение с другим полем")]
        public async global::System.Threading.Tasks.Task ЗаписьВПолеЧерезВыражениеСДругимПолем()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("запись в поле через выражение с другим полем", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 19
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 20
        await testRunner.GivenAsync("я скомпилировал программу \"features/structs/struct_field_expression.ww\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Пусть ");
#line hidden
#line 21
        await testRunner.WhenAsync("я выполняю программу", ((string)(null)), ((global::Reqnroll.Table)(null)), "Когда ");
#line hidden
#line 22
        await testRunner.ThenAsync("я увижу вывод 7", ((string)(null)), ((global::Reqnroll.Table)(null)), "Тогда ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="структура как параметр функции")]
        [global::Xunit.TraitAttribute("FeatureTitle", "структуры")]
        [global::Xunit.TraitAttribute("Description", "структура как параметр функции")]
        public async global::System.Threading.Tasks.Task СтруктураКакПараметрФункции()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("структура как параметр функции", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 24
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 25
        await testRunner.GivenAsync("я скомпилировал программу \"features/structs/struct_param.ww\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Пусть ");
#line hidden
#line 26
        await testRunner.WhenAsync("я выполняю программу", ((string)(null)), ((global::Reqnroll.Table)(null)), "Когда ");
#line hidden
#line 27
        await testRunner.ThenAsync("я увижу вывод 30", ((string)(null)), ((global::Reqnroll.Table)(null)), "Тогда ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="структура как возвращаемое значение функции")]
        [global::Xunit.TraitAttribute("FeatureTitle", "структуры")]
        [global::Xunit.TraitAttribute("Description", "структура как возвращаемое значение функции")]
        public async global::System.Threading.Tasks.Task СтруктураКакВозвращаемоеЗначениеФункции()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("структура как возвращаемое значение функции", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 29
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 30
        await testRunner.GivenAsync("я скомпилировал программу \"features/structs/struct_return.ww\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Пусть ");
#line hidden
#line 31
        await testRunner.WhenAsync("я выполняю программу", ((string)(null)), ((global::Reqnroll.Table)(null)), "Когда ");
#line hidden
#line 32
        await testRunner.ThenAsync("я увижу вывод 56", ((string)(null)), ((global::Reqnroll.Table)(null)), "Тогда ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="пустая структура")]
        [global::Xunit.TraitAttribute("FeatureTitle", "структуры")]
        [global::Xunit.TraitAttribute("Description", "пустая структура")]
        public async global::System.Threading.Tasks.Task ПустаяСтруктура()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("пустая структура", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 34
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 35
        await testRunner.GivenAsync("я скомпилировал программу \"features/structs/struct_empty.ww\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Пусть ");
#line hidden
#line 36
        await testRunner.WhenAsync("я выполняю программу", ((string)(null)), ((global::Reqnroll.Table)(null)), "Когда ");
#line hidden
#line 37
        await testRunner.ThenAsync("я увижу вывод ok", ((string)(null)), ((global::Reqnroll.Table)(null)), "Тогда ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="множественные переменные одного типа структуры")]
        [global::Xunit.TraitAttribute("FeatureTitle", "структуры")]
        [global::Xunit.TraitAttribute("Description", "множественные переменные одного типа структуры")]
        public async global::System.Threading.Tasks.Task МножественныеПеременныеОдногоТипаСтруктуры()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "7";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("множественные переменные одного типа структуры", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 39
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 40
        await testRunner.GivenAsync("я скомпилировал программу \"features/structs/struct_multiple_vars.ww\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Пусть ");
#line hidden
#line 41
        await testRunner.WhenAsync("я выполняю программу", ((string)(null)), ((global::Reqnroll.Table)(null)), "Когда ");
#line hidden
#line 42
        await testRunner.ThenAsync("я увижу вывод 14", ((string)(null)), ((global::Reqnroll.Table)(null)), "Тогда ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="ошибка компиляции — литерал с недостающими значениями")]
        [global::Xunit.TraitAttribute("FeatureTitle", "структуры")]
        [global::Xunit.TraitAttribute("Description", "ошибка компиляции — литерал с недостающими значениями")]
        public async global::System.Threading.Tasks.Task ОшибкаКомпиляцииЛитералСНедостающимиЗначениями()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "8";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("ошибка компиляции — литерал с недостающими значениями", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 44
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 45
        await testRunner.GivenAsync("я попытался скомпилировать программу \"features/structs/struct_literal_missing.ww\"" +
                        "", ((string)(null)), ((global::Reqnroll.Table)(null)), "Пусть ");
#line hidden
#line 46
        await testRunner.ThenAsync("компиляция завершилась с кодом 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "Тогда ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="ошибка компиляции — литерал с лишними значениями")]
        [global::Xunit.TraitAttribute("FeatureTitle", "структуры")]
        [global::Xunit.TraitAttribute("Description", "ошибка компиляции — литерал с лишними значениями")]
        public async global::System.Threading.Tasks.Task ОшибкаКомпиляцииЛитералСЛишнимиЗначениями()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "9";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("ошибка компиляции — литерал с лишними значениями", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 48
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 49
        await testRunner.GivenAsync("я попытался скомпилировать программу \"features/structs/struct_literal_extra.ww\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Пусть ");
#line hidden
#line 50
        await testRunner.ThenAsync("компиляция завершилась с кодом 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "Тогда ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="ошибка компиляции — несовместимый тип в литерале")]
        [global::Xunit.TraitAttribute("FeatureTitle", "структуры")]
        [global::Xunit.TraitAttribute("Description", "ошибка компиляции — несовместимый тип в литерале")]
        public async global::System.Threading.Tasks.Task ОшибкаКомпиляцииНесовместимыйТипВЛитерале()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "10";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("ошибка компиляции — несовместимый тип в литерале", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 52
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 53
        await testRunner.GivenAsync("я попытался скомпилировать программу \"features/structs/struct_literal_type_mismat" +
                        "ch.ww\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Пусть ");
#line hidden
#line 54
        await testRunner.ThenAsync("компиляция завершилась с кодом 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "Тогда ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="ошибка компиляции — несовместимый тип при присваивании поля")]
        [global::Xunit.TraitAttribute("FeatureTitle", "структуры")]
        [global::Xunit.TraitAttribute("Description", "ошибка компиляции — несовместимый тип при присваивании поля")]
        public async global::System.Threading.Tasks.Task ОшибкаКомпиляцииНесовместимыйТипПриПрисваиванииПоля()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "11";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("ошибка компиляции — несовместимый тип при присваивании поля", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 56
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 57
        await testRunner.GivenAsync("я попытался скомпилировать программу \"features/structs/struct_field_assign_type_m" +
                        "ismatch.ww\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Пусть ");
#line hidden
#line 58
        await testRunner.ThenAsync("компиляция завершилась с кодом 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "Тогда ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="ошибка компиляции — запись в поле константы")]
        [global::Xunit.TraitAttribute("FeatureTitle", "структуры")]
        [global::Xunit.TraitAttribute("Description", "ошибка компиляции — запись в поле константы")]
        public async global::System.Threading.Tasks.Task ОшибкаКомпиляцииЗаписьВПолеКонстанты()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "12";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("ошибка компиляции — запись в поле константы", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 60
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 61
        await testRunner.GivenAsync("я попытался скомпилировать программу \"features/structs/struct_const_field_write.w" +
                        "w\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Пусть ");
#line hidden
#line 62
        await testRunner.ThenAsync("компиляция завершилась с кодом 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "Тогда ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="ошибка компиляции — обращение к несуществующему полю")]
        [global::Xunit.TraitAttribute("FeatureTitle", "структуры")]
        [global::Xunit.TraitAttribute("Description", "ошибка компиляции — обращение к несуществующему полю")]
        public async global::System.Threading.Tasks.Task ОшибкаКомпиляцииОбращениеКНесуществующемуПолю()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "13";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("ошибка компиляции — обращение к несуществующему полю", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 64
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 65
        await testRunner.GivenAsync("я попытался скомпилировать программу \"features/structs/struct_unknown_field.ww\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Пусть ");
#line hidden
#line 66
        await testRunner.ThenAsync("компиляция завершилась с кодом 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "Тогда ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="структура с полем-массивом — чтение")]
        [global::Xunit.TraitAttribute("FeatureTitle", "структуры")]
        [global::Xunit.TraitAttribute("Description", "структура с полем-массивом — чтение")]
        public async global::System.Threading.Tasks.Task СтруктураСПолем_МассивомЧтение()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "14";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("структура с полем-массивом — чтение", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 68
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 69
        await testRunner.GivenAsync("я скомпилировал программу \"features/structs/struct_with_array.ww\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Пусть ");
#line hidden
#line 70
        await testRunner.WhenAsync("я выполняю программу", ((string)(null)), ((global::Reqnroll.Table)(null)), "Когда ");
#line hidden
#line 71
        await testRunner.ThenAsync("я увижу вывод 13", ((string)(null)), ((global::Reqnroll.Table)(null)), "Тогда ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="структура с полем-массивом — запись в элемент массива")]
        [global::Xunit.TraitAttribute("FeatureTitle", "структуры")]
        [global::Xunit.TraitAttribute("Description", "структура с полем-массивом — запись в элемент массива")]
        public async global::System.Threading.Tasks.Task СтруктураСПолем_МассивомЗаписьВЭлементМассива()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "15";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("структура с полем-массивом — запись в элемент массива", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 73
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 74
        await testRunner.GivenAsync("я скомпилировал программу \"features/structs/struct_with_array_write.ww\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Пусть ");
#line hidden
#line 75
        await testRunner.WhenAsync("я выполняю программу", ((string)(null)), ((global::Reqnroll.Table)(null)), "Когда ");
#line hidden
#line 76
        await testRunner.ThenAsync("я увижу вывод 10", ((string)(null)), ((global::Reqnroll.Table)(null)), "Тогда ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="структура с массивом структур — чтение через цепочку")]
        [global::Xunit.TraitAttribute("FeatureTitle", "структуры")]
        [global::Xunit.TraitAttribute("Description", "структура с массивом структур — чтение через цепочку")]
        public async global::System.Threading.Tasks.Task СтруктураСМассивомСтруктурЧтениеЧерезЦепочку()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "16";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("структура с массивом структур — чтение через цепочку", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 78
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 79
        await testRunner.GivenAsync("я скомпилировал программу \"features/structs/struct_with_nested_array.ww\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Пусть ");
#line hidden
#line 80
        await testRunner.WhenAsync("я выполняю программу", ((string)(null)), ((global::Reqnroll.Table)(null)), "Когда ");
#line hidden
#line 81
        await testRunner.ThenAsync("я увижу вывод 58", ((string)(null)), ((global::Reqnroll.Table)(null)), "Тогда ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="структура с массивом структур — запись через цепочку")]
        [global::Xunit.TraitAttribute("FeatureTitle", "структуры")]
        [global::Xunit.TraitAttribute("Description", "структура с массивом структур — запись через цепочку")]
        public async global::System.Threading.Tasks.Task СтруктураСМассивомСтруктурЗаписьЧерезЦепочку()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "17";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("структура с массивом структур — запись через цепочку", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 83
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 84
        await testRunner.GivenAsync("я скомпилировал программу \"features/structs/struct_with_nested_array_write.ww\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Пусть ");
#line hidden
#line 85
        await testRunner.WhenAsync("я выполняю программу", ((string)(null)), ((global::Reqnroll.Table)(null)), "Когда ");
#line hidden
#line 86
        await testRunner.ThenAsync("я увижу вывод 99", ((string)(null)), ((global::Reqnroll.Table)(null)), "Тогда ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await СтруктурыFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await СтруктурыFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
